---
- name: Update apt cache.
  package:
    update_cache: true
    cache_valid_time: 3600

- include_tasks: ssh_no_port.yml
  when: security_ssh_enabled | bool

- include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

- include_tasks: autoupdate.yml
  when: security_autoupdate_enabled | bool

- include_tasks: firewall.yml
  when: security_ufw_enabled | bool
