---
- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded

- name: reload ufw
  service:
    name: ufw
    state: reloaded
