---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      package:
        update_cache: true
        cache_valid_time: 600

    - name: Ensure build dependencies are installed.
      package:
        name:
          - openssh-server
          - openssh-client
        state: present

    - include_vars:
        file: "{{ item }}"
      with_items:
        - ../../defaults/main.yml

    - name: Ser ansible_port fact.
      set_fact:
        ansible_port: "{{ security_ssh_port }}"

  roles:
    - role: rafael-c-alexandre.security
