---
name: CI

'on':
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  lint:
    uses: rafael-c-alexandre/ansible-devops/.github/workflows/lint.yml@main

  molecule:
    needs: lint
    uses: rafael-c-alexandre/ansible-devops/.github/workflows/molecule.yml@main
