---
name: Release

'on':
  push:
    tags:
      - '*'

jobs:

  release:
    uses: rafael-c-alexandre/ansible-roles-devops/.github/workflows/release.yml@main
    secrets:
      GALAXY_PAT: ${{ secrets.GALAXY_PAT }}
